# Generated by Django 3.1.7 on 2021-03-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprouts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='last_used_date',
            field=models.DateField(verbose_name='Date of last use'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
